apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hrm-project

resources:
  - ../../base
  - ecr-cronjob.yaml
  - route.yaml

patchesStrategicMerge:
  - storage-patch.yaml
  - ingress-remove.yaml
