apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_format=row
    bind-address=0.0.0.0
    expire_logs_days=7

    # --- AWS Aurora MySQL 호환성을 위한 MariaDB 고유 기능 비활성화 ---
    binlog_annotate_row_events = OFF
    replicate_annotate_row_events = OFF
    binlog_checksum = NONE
    master_verify_checksum = OFF
  
